server:
  port: ${PORT_MS:8080}

app:
  realm: digitalmedia

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8082/}realms/${app.realm}
            authorization-uri: http://localhost:8082/realms/${app.realm}/protocol/openid-connect/auth
            user-name-attribute: preferred_username
        registration:
          gateway-api:
            provider: keycloak
            client-id: api-gateway
            client-secret: 745MnUKUHG5bp0RAwS8BjTkq9WrPvYDb
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8080/login/oauth2/code/keycloak'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: moviesRoute
          uri: lb://movies-service
          predicates:
            - Path=/movies/**
        - id: billsRoute
          uri: lb://bills-service
          predicates:
            - Path=/bills/**
        - id: usersRoute
          uri: lb://users-service
          predicates:
            - Path=/users/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
